name: az cli auto deployment for goweb01

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
#   push:
#     branches: 
#       [ main ]
#     paths:
#     - '**'
#     - '.github/workflows/deploy.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      container_image: ${{ steps.build.outputs.container_image}}

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Checkout to the branch
        uses: actions/checkout@v2
    
      - uses: imjasonh/setup-ko@v0.4

      - name: Set version env
        run: echo "VERSION=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV

      - name: Build
        id: build
        run: echo "::set-output name=container_image::$(ko publish .)"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
     
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}          

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n ${{ secrets.CONTAINERAPPS_NAME }} -g ${{ secrets.AZURE_RESOUCE_GROUP }} --server ${{ secrets.REGISTRY_SERVER }} --username ${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_PASSWORD }}
            az containerapp update -n ${{ secrets.CONTAINERAPPS_NAME }} -g ${{ secrets.AZURE_RESOUCE_GROUP }} --image ${{ needs.build.outputs.container_image }}
            az logout
            az cache purge
            az account clear
